version: 0.0
os: linux
files:
  - source: /jenkins-deploy-api.jar
    destination: /home/ec2-user/apps/prod
  - source: /jenkins-deploy-api.conf
    destination: /home/ec2-user/apps/prod
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy-before.sh
      timeout: 300
      runas: root